apiVersion: v1
kind: Service
metadata:
  name: sample-backend-service
  namespace: sample-app-development
  labels:
    app: sample-backend
spec:
  selector:
    app: sample-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: sample-frontend-service
  namespace: sample-app-development
  labels:
    app: sample-frontend
spec:
  selector:
    app: sample-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort
